package com.pepe.dao.model;
// Generated 31.10.2016 12:07:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teams generated by hbm2java
 */
@Entity
@Table(name="teams"
    ,catalog="dbs"
)
public class Teams  implements java.io.Serializable {


     private Integer id;
     private Players players;
     private String name;
     private String skratka;
     private Date regDate;
     private Set<Players> playerses = new HashSet<Players>(0);

    public Teams() {
    }

	
    public Teams(String name, String skratka, Date regDate) {
        this.name = name;
        this.skratka = skratka;
        this.regDate = regDate;
    }
    public Teams(Players players, String name, String skratka, Date regDate, Set<Players> playerses) {
       this.players = players;
       this.name = name;
       this.skratka = skratka;
       this.regDate = regDate;
       this.playerses = playerses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="kapitan_id")
    public Players getPlayers() {
        return this.players;
    }
    
    public void setPlayers(Players players) {
        this.players = players;
    }

    
    @Column(name="name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="skratka", nullable=false, length=128)
    public String getSkratka() {
        return this.skratka;
    }
    
    public void setSkratka(String skratka) {
        this.skratka = skratka;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="reg_date", nullable=false, length=19)
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teams")
    public Set<Players> getPlayerses() {
        return this.playerses;
    }
    
    public void setPlayerses(Set<Players> playerses) {
        this.playerses = playerses;
    }




}


